version: '3'
services:
  smtp:
      image: industrieco/exim-relay
      restart: always
      ports:
        - "25:8025"
      hostname: sekizkirk.io

  db:
      image: postgres:12.0-alpine
      ports:
          - "5432:5432"
      environment:
          - POSTGRES_DB=sekizkirk
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
  web:
      build: backend/sekizkirk
      command: gunicorn sekizkirk.wsgi:application --bind 0.0.0.0:8000
      expose:
          - 8000
      depends_on:
          - db

  scraper:
      build: backend/scraper-service
      command: python sekizkirk.py --path /sekizkirk_cache --period 1w --silent
      volumes:
          - /tmp/sk:/sekizkirk_cache
      expose:
          - 8001
      depends_on:
          - web

  renderer:
      build: backend/mail-renderer
      expose:
          - 3000
      environment:
          - NODE_ENV=production

  sekizkirk_fe:
      build: frontend
      command: sleep infinity
      volumes:
        - static_files:/sekizkirk_fe/dist
      environment:
          - NODE_ENV=production

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/certbot/conf:/etc/letsencrypt
      - /etc/certbot/www:/var/www/certbot
      - static_files:/etc/nginx/html
      - /tmp/sk/data.json:/etc/nginx/html/data.json
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - web
      - sekizkirk_fe

  certbot:
    volumes:
      - /etc/certbot/conf:/etc/letsencrypt
      - /etc/certbot/www:/var/www/certbot
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


volumes:
    static_files:
