version: '3'
services:
  smtp:
      image: industrieco/exim-relay
      restart: always
      ports:
        - "25:8025"
      hostname: sekizkirk.io

  db:
      image: postgres:12.0-alpine
      ports:
          - "5432:5432"
      environment:
          - POSTGRES_DB=sekizkirk
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
  web:
      image: sekizkirk_be:1.1
      command: gunicorn sekizkirk.wsgi:application --bind 0.0.0.0:8000
      volumes:
          - /tmp/sk:/sekizkirk_cache
      expose:
          - 8000
      depends_on:
          - db

  scraper:
      build: scraper-service
      command: python sekizkirk.py --path /sekizkirk_cache --period 1w --silent
      volumes:
          - /tmp/sk:/sekizkirk_cache
      expose:
          - 8001
      depends_on:
          - web

  renderer:
      build: mail-renderer
      expose:
          - 3000

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./dist:/etc/nginx/html
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - web


  certbot:
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


