version: "3"

services:
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=postgres
    web:
        build: .
        command: sleep infinity
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
