# Generated by Django 3.1 on 2020-11-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_name', models.EmailField(max_length=254)),
                ('schedule', models.JSONField()),
            ],
        ),
    ]
