# Generated by Django 3.1 on 2020-11-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_handler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email_name',
            new_name='email',
        ),
    ]
